name: Vulnerability Scan Workflow

# Trigger the action on push and pull request events
on:
  push:
    branches:
      - main  # You can specify which branch you want to trigger the action on (e.g., 'main')
  pull_request:
    branches:
      - main  # You can specify which branch to listen for pull requests (e.g., 'main')

jobs:
  scan:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the appropriate Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run the vulnerability scan (make sure scan.py and config.yml are in the repo)
      - name: Run vulnerability scan
        run: |
          python3 scan.py
